#JMS info

jms:
  host: "0.0.0.0"
  port: "61616"
  user: "admin"
  password: "admin"
  
jms2:
  host: "localhost"
  port: "5540"
  user: "admin"
  password: "admin"
  trust:
    path: "/Users/viswabrahmana/Siva/mule-demo/server-ca-truststore.jks"
    pass: "securepass"
  url: "tcp://${jms2.host}:${jms2.port}?sslEnabled=true&trustStorePath=${jms2.trust.path}&trustStorePassword=${jms2.trust.pass}"
  
jndi.factory: "org.apache.activemq.artemis.jndi.ActiveMQInitialContextFactory"

  